import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/pages/Home.module.scss'
import Input from "../components/Input";
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.form}>
            <div className={styles.form__container}>
                <h2 className={styles.form__title}>Начать</h2>
                <div className={styles.input__block}>
                    <h3 className={styles.input__title}>Ваше имя</h3>
                    <Input  placeholder={"Как вас зовут?"}/>
                </div>
            </div>
            <div className={styles.button__container}>
                <Button title={"Открыть калькулятор"} />
                <Button title={"Открыть генератор"} />
            </div>
        </div>
      </main>
    </div>
  )
}

export default Home
